language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2
- hhvm
matrix:
  allow_failures:
  - php: hhvm
  fast_finish: true
before_script:
- composer self-update
- composer install --dev
- composer require --dev php-coveralls/php-coveralls
notifications:
  email:
    recipients:
    - eric@ericbaker.me
    on_success: change